language: java
sudo: required
before_script:
  - sudo apt-get update
  - sudo apt-get install mvn
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
install:
  - mvn package -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn test
